# Lab 4: Advanced Neural Nets
### Шевченко Юлія, ФІ-31мн

### Lab Task:

1. _**Завдання щодо генерації текстів або машинного перекладу (на вибір) на базі рекурентних мереж або трансформерів (на вибір)**_. Вирішити завдання щодо генерації текстів або машинного перекладу. Особливо вітаються україномовні моделі.  
2. Провести експерименти з моделями бібліотеки HF Transformers за допомогою (наприклад) Pipeline модуля.
3. _**Завдання щодо генерації або стилізації зображень (на вибір)**_. Вирішити завдання перенесення стилю або генерації зображень (архітектура за вашим вибором: GAN/DCGAN/VAE).

In [1]:
# All the imports for the task
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
from transformers import pipeline

### Task 2

In [2]:
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [3]:
positive = 'Python -- great programming language'
classifier(positive)

[{'label': 'POSITIVE', 'score': 0.999783456325531}]

In [4]:
negative = 'It was not his best decision to do that'
classifier(negative)

[{'label': 'NEGATIVE', 'score': 0.9997938275337219}]

In [5]:
exp_model = 'distilbert-base-uncased-finetuned-sst-2-english'

In [6]:
model = TFAutoModelForSequenceClassification.from_pretrained(exp_model)
tokenizer = AutoTokenizer.from_pretrained(exp_model)

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [7]:
inputs = tokenizer([positive, negative])

inputs

{'input_ids': [[101, 18750, 1011, 1011, 2307, 4730, 2653, 102], [101, 2009, 2001, 2025, 2010, 2190, 3247, 2000, 2079, 2008, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [8]:
inputs_with_padding = tokenizer([positive, negative], padding = True, truncation = True, max_length = 256, return_tensors="tf")

inputs_with_padding

{'input_ids': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[  101, 18750,  1011,  1011,  2307,  4730,  2653,   102,     0,
            0,     0],
       [  101,  2009,  2001,  2025,  2010,  2190,  3247,  2000,  2079,
         2008,   102]])>, 'attention_mask': <tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])>}

In [9]:
outputs = model(inputs_with_padding)

outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4.066877 ,  4.370734 ],
       [ 4.688553 , -3.7980757]], dtype=float32)>, hidden_states=None, attentions=None)

In [10]:
predictions = tf.nn.softmax(outputs[0], axis=-1)

predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.1652009e-04, 9.9978346e-01],
       [9.9979383e-01, 2.0616478e-04]], dtype=float32)>